/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "accent-gold": "#C5A059",
        "accent-terracotta": "#BF360C",
        "background": "#fbf9f4",
        "commerce-primary": "#3F2B21",
        "commerce-secondary": "#7A5230",
        "commerce-background": "#FBF7F1",
        "commerce-surface": "#FFFFFF",
        "commerce-surface-muted": "#F7F3EC",
        "commerce-border": "#E8E0D5",
        "commerce-text": "#2D2925",
        "commerce-muted": "#756D66",
        "commerce-sale": "#B94732",
        "commerce-sale-soft": "#F8EAE4",
        "ui-ink": "#333333",
        "ui-text": "#434343",
        "ui-muted": "#777777",
        "ui-soft": "#FAFAF8",
        "ui-surface": "#FFFFFF",
        "ui-border": "#E5E5E5",
        "ui-border-soft": "#EEEEEE",
        "ui-walnut": "#4A3A31",
        "ui-accent": "#BFA37C",
        "ui-sale": "#F41919",
        "ui-success": "#2F7D32",
        "ui-warning": "#9A6A16",
        "ui-error": "#B94732",
        "ui-info": "#3966B8",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f2f1ec",
        "inverse-primary": "#e7bdb1",
        "inverse-surface": "#30312e",
        "on-background": "#1b1c19",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#d4ada1",
        "on-primary-fixed": "#2c160e",
        "on-primary-fixed-variant": "#5d4037",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#785a1a",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5d4201",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#504441",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ff9a7f",
        "on-tertiary-fixed": "#3b0800",
        "on-tertiary-fixed-variant": "#881f00",
        "outline": "#827470",
        "outline-variant": "#d4c3be",
        "primary": "#442a22",
        "primary-container": "#5d4037",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#e7bdb1",
        "secondary": "#775a19",
        "secondary-container": "#fed488",
        "secondary-fixed": "#ffdea5",
        "secondary-fixed-dim": "#e9c176",
        "surface": "#fbf9f4",
        "surface-beige": "#F2EEE5",
        "surface-ivory": "#F9F7F2",
        "surface-bright": "#fbf9f4",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-container-low": "#f5f3ee",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dbdad5",
        "surface-tint": "#77574d",
        "surface-variant": "#e4e2dd",
        "tertiary": "#601300",
        "tertiary-container": "#881f00",
        "tertiary-fixed": "#ffdbd1",
        "tertiary-fixed-dim": "#ffb5a1",
        "text-charcoal": "#333333",
        "text-muted": "#666666"
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'serif'],
        sans: ['Montserrat', 'sans-serif'],
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px"
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        "commerce-card": "8px",
        "commerce-control": "6px",
        "ui-card": "12px",
        "ui-control": "7px",
      },
      boxShadow: {
        "commerce-card": "0 1px 2px rgba(63, 43, 33, 0.05)",
        "commerce-card-hover": "0 10px 24px rgba(63, 43, 33, 0.08)",
        "ui-soft": "0 1px 2px rgba(0, 0, 0, 0.03)",
        "ui-popover": "0 18px 42px rgba(0, 0, 0, 0.10)",
      },
      transitionTimingFunction: {
        commerce: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
