import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import path from 'path';
import { fileURLToPath } from 'url';
import prisma from './prismaClient.js';
import authRoutes from './routes/auth.routes.js';
import productRoutes from './routes/product.routes.js';
import orderRoutes from './routes/order.routes.js';
import categoryRoutes from './routes/category.routes.js';
import uploadRoutes from './routes/upload.routes.js';
import customerRoutes from './routes/customer.routes.js';
import adminAccountRoutes from './routes/admin-account.routes.js';
import permissionRoutes from './routes/permission.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import addressRoutes from './routes/address.routes.js';
import wishlistRoutes from './routes/wishlist.routes.js';
import paymentRoutes from './routes/payment.routes.js';
import reviewRoutes from './routes/review.routes.js';
import aiAdvisorRoutes from './routes/aiAdvisor.routes.js';
import consultationRequestRoutes from './routes/consultationRequest.routes.js';
import notificationRoutes from './routes/notification.routes.js';
import promotionRoutes from './routes/promotion.routes.js';
import voucherRoutes from './routes/voucher.routes.js';
import publicVoucherRoutes from './routes/public-voucher.routes.js';
import voucherDefinitionRoutes from './routes/voucher-definition.routes.js';
import voucherClaimRoutes from './routes/voucher-claim.routes.js';
import voucherAssignmentRoutes from './routes/voucher-assignment.routes.js';
import loyaltyRoutes from './routes/loyalty.routes.js';
import { rewardCatalogRoutes, rewardRedemptionRoutes } from './routes/reward-catalog.routes.js';
import { adminSupportConversationRoutes, supportConversationRoutes } from './routes/supportConversation.routes.js';
import { isAllowedOrigin } from './utils/originPolicy.js';
import { requestContext } from './middlewares/requestContext.middleware.js';
import { requestLogger } from './middlewares/requestLogger.middleware.js';
import { errorHandler, notFoundHandler } from './middlewares/error.middleware.js';
import { createHealthRouter } from './routes/health.routes.js';
import { configureCloudinary } from './config/cloudinary.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const createApp = ({ getIsShuttingDown = () => false } = {}) => {
  const app = express();
  const trustProxyHops = Number.parseInt(process.env.TRUST_PROXY_HOPS || '1', 10);
  if (process.env.NODE_ENV === 'production' && Number.isSafeInteger(trustProxyHops) && trustProxyHops >= 1) app.set('trust proxy', trustProxyHops);

  app.disable('x-powered-by');
  app.use(helmet({ contentSecurityPolicy: false, hsts: process.env.NODE_ENV === 'production' ? undefined : false, crossOriginResourcePolicy: { policy: 'cross-origin' }, referrerPolicy: { policy: 'strict-origin-when-cross-origin' } }));
  app.use(requestContext);
  app.use(cors({ origin: (origin, callback) => !origin || isAllowedOrigin(origin) ? callback(null, true) : callback(new Error('Not allowed by CORS')), credentials: true }));
  app.use(requestLogger);
  app.use(express.json({ limit: '256kb' }));
  app.use(express.urlencoded({ extended: false, limit: '64kb', parameterLimit: 100 }));
  configureCloudinary();
  app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
  app.use(createHealthRouter({ prisma, getIsShuttingDown }));

  app.use('/api/auth', authRoutes);
  app.use('/api/products', productRoutes);
  app.use('/api/orders', orderRoutes);
  app.use('/api/categories', categoryRoutes);
  app.use('/api/uploads', uploadRoutes);
  app.use('/api/customers', customerRoutes);
  app.use('/api/admin-accounts', adminAccountRoutes);
  app.use('/api/permissions', permissionRoutes);
  app.use('/api/dashboard', dashboardRoutes);
  app.use('/api/addresses', addressRoutes);
  app.use('/api/wishlist', wishlistRoutes);
  app.use('/api/payment', paymentRoutes);
  app.use('/api/reviews', reviewRoutes);
  app.use('/api/ai-advisor', aiAdvisorRoutes);
  app.use('/api/consultation-requests', consultationRequestRoutes);
  app.use('/api/notifications', notificationRoutes);
  app.use('/api/promotions', promotionRoutes);
  app.use('/api/vouchers', voucherRoutes);
  app.use('/api/public-vouchers', publicVoucherRoutes);
  app.use('/api/voucher-definitions', voucherDefinitionRoutes);
  app.use('/api/voucher-claims', voucherClaimRoutes);
  app.use('/api/voucher-assignments', voucherAssignmentRoutes);
  app.use('/api/loyalty', loyaltyRoutes);
  app.use('/api/reward-catalog', rewardCatalogRoutes);
  app.use('/api/reward-redemptions', rewardRedemptionRoutes);
  app.use('/api/support/conversations', supportConversationRoutes);
  app.use('/api/admin/support/conversations', adminSupportConversationRoutes);
  app.use(notFoundHandler);
  app.use(errorHandler);
  return app;
};
