import { useCallback, useEffect, useState } from 'react';
import { voucherService } from '../../services/api/voucherService';
import useFinancialRefresh, { invalidateFinancialData } from '../../hooks/useFinancialRefresh';
const money = (value) => `${new Intl.NumberFormat('vi-VN').format(Number(value || 0))} ₫`;
const date = (value) => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium' }).format(new Date(value)) : null;
export default function PublicVouchers() {
  const [items, setItems] = useState(null); const [error, setError] = useState(''); const [claiming, setClaiming] = useState(null);
  const load = useCallback(async () => { try { setError(''); const response = await voucherService.listPublicVouchers(); setItems(Array.isArray(response?.data) ? response.data : []); } catch (requestError) { setError(requestError?.data?.error?.message || 'Không thể tải ưu đãi công khai.'); } }, []);
  useEffect(() => { load(); }, [load]); useFinancialRefresh(load);
  const claim = async (item) => { if (claiming) return; setClaiming(item.voucherDefinitionId); try { await voucherService.claimVoucher(item.voucherDefinitionId); invalidateFinancialData(); await load(); window.dispatchEvent(new CustomEvent('show-toast', { detail: { type: 'success', message: 'Đã nhận Voucher.' } })); } catch (requestError) { setError(requestError?.data?.error?.message || 'Không thể nhận Voucher.'); } finally { setClaiming(null); } };
  return <main className="mx-auto max-w-container-max py-2"><header><h2 className="text-2xl font-bold text-[#333333]">Ưu đãi công khai</h2><p className="mt-2 text-sm text-ui-muted">Nhận ưu đãi đang áp dụng vào tài khoản của bạn.</p></header>{error ? <div className="mt-6 rounded border border-error bg-error-container p-4 text-sm" role="alert">{error}<button className="ui-button-secondary ml-3" onClick={load}>Thử lại</button></div> : null}{items === null ? <div className="mt-6 grid gap-4 sm:grid-cols-2" aria-busy="true"><div className="ui-skeleton h-60 rounded-[12px]" /><div className="ui-skeleton h-60 rounded-[12px]" /></div> : items.length ? <ul className="mt-6 grid gap-4 sm:grid-cols-2">{items.map((item) => { const claimed = item.claimStatus === 'CLAIMED'; return <li key={item.voucherDefinitionId} className="ui-card flex min-w-0 flex-col p-5"><div className="flex justify-between gap-3"><span className="ui-badge">PUBLIC</span><span className="ui-badge">{claimed ? 'ĐÃ NHẬN' : 'CÓ THỂ NHẬN'}</span></div><h3 className="mt-4 text-lg font-bold text-[#333333]">{item.name}</h3>{item.description ? <p className="mt-2 text-sm leading-6 text-ui-muted">{item.description}</p> : null}<dl className="mt-4 space-y-2 border-t border-[#eeeeee] pt-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-ui-muted">Ưu đãi</dt><dd className="font-semibold">{item.discountType === 'PERCENTAGE' ? `Giảm ${item.discountValueVnd}%` : `Giảm ${money(item.discountValueVnd)}`}</dd></div>{item.minimumOrderAmountVnd != null ? <div className="flex justify-between gap-3"><dt className="text-ui-muted">Đơn tối thiểu</dt><dd>{money(item.minimumOrderAmountVnd)}</dd></div> : null}{item.validTo ? <div className="flex justify-between gap-3"><dt className="text-ui-muted">Nhận đến</dt><dd>{date(item.validTo)}</dd></div> : null}</dl><button className="ui-button-primary mt-5 w-full" disabled={claimed || claiming === item.voucherDefinitionId} onClick={() => claim(item)}>{claimed ? 'Đã nhận' : claiming === item.voucherDefinitionId ? 'Đang nhận...' : 'Nhận Voucher'}</button></li>; })}</ul> : <div className="ui-empty-state mt-6" role="status">Hiện chưa có ưu đãi công khai.</div>}</main>;
}
