import { useCallback, useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import useFinancialRefresh, { invalidateFinancialData } from '../../hooks/useFinancialRefresh';
import { loyaltyService } from '../../services/api/loyaltyService';

const PAGE_SIZE = 20;
const HISTORY_TYPES = { EARN_ORDER: 'Điểm từ đơn hàng', REDEEM_VOUCHER: 'Đổi điểm nhận thưởng', REVERSE_ORDER: 'Hoàn điểm', ADMIN_ADJUSTMENT: 'Điều chỉnh điểm' };
const formatPoints = (value) => new Intl.NumberFormat('vi-VN').format(Number(value || 0));
const formatMoney = (value) => `${new Intl.NumberFormat('vi-VN').format(Number(value || 0))} ₫`;
const formatDate = (value) => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium' }).format(new Date(value)) : null;
const errorMessage = (error, fallback) => error?.data?.error?.message || error?.message || fallback;
const redemptionMessage = (error) => ({ INSUFFICIENT_REWARD_POINTS: 'Điểm thưởng hiện có không đủ để đổi phần thưởng này.', REWARD_CATALOG_ITEM_UNAVAILABLE: 'Phần thưởng này đã hết lượt đổi.', REWARD_CATALOG_ITEM_INACTIVE: 'Phần thưởng này hiện không khả dụng.' }[error?.data?.error?.code] || errorMessage(error, 'Không thể đổi phần thưởng lúc này.'));

function Skeleton({ className = 'h-20' }) { return <div className={`ui-skeleton ${className} rounded-[12px]`} />; }

function RewardCard({ item, balance, redeeming, onRedeem }) {
  const insufficient = balance < Number(item.pointCost || 0);
  const numericInventory = item.remainingQuantity ?? (item.inventoryLimit != null && item.redeemedCount != null ? Math.max(Number(item.inventoryLimit) - Number(item.redeemedCount), 0) : null);
  const explicitExhaustion = numericInventory === 0;
  const disabled = insufficient || explicitExhaustion || redeeming;
  const buttonLabel = redeeming ? 'Đang đổi...' : explicitExhaustion ? 'Hết số lượng' : insufficient ? 'Không đủ điểm' : 'Đổi thưởng';
  const voucher = item.voucher || {};
  const discount = voucher.discountType === 'PERCENTAGE' ? `Giảm ${voucher.discountValueVnd}%` : `Giảm ${formatMoney(voucher.discountValueVnd)}`;
  const expiry = voucher.fixedExpiresAt ? `Hết hạn ${formatDate(voucher.fixedExpiresAt)}` : item.validityDays ? `Có hiệu lực ${item.validityDays} ngày sau khi nhận` : null;
  return <li className="ui-card flex min-w-0 flex-col p-5">
    <div className="flex items-start justify-between gap-3"><span className="ui-badge">PHẦN THƯỞNG</span><span className="text-xs font-semibold text-[#777777]">{formatPoints(item.pointCost)} điểm</span></div>
    <h4 className="mt-4 break-words text-lg font-bold text-[#333333]">{voucher.name || voucher.code}</h4>
    {voucher.description ? <p className="mt-2 break-words text-sm leading-6 text-ui-muted">{voucher.description}</p> : null}
    <dl className="mt-4 space-y-2 border-t border-[#eeeeee] pt-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-ui-muted">Ưu đãi</dt><dd className="text-right font-semibold text-[#333333]">{discount}</dd></div>{voucher.minimumOrderAmountVnd != null ? <div className="flex justify-between gap-3"><dt className="text-ui-muted">Đơn tối thiểu</dt><dd className="text-right text-[#555555]">{formatMoney(voucher.minimumOrderAmountVnd)}</dd></div> : null}{expiry ? <div className="flex justify-between gap-3"><dt className="text-ui-muted">Thời hạn</dt><dd className="text-right text-[#555555]">{expiry}</dd></div> : null}{numericInventory != null ? <div className="flex justify-between gap-3"><dt className="text-ui-muted">Còn lại</dt><dd className="text-right text-[#555555]">{numericInventory}</dd></div> : null}</dl>
    <button type="button" className="ui-button-primary mt-5 w-full" disabled={disabled} onClick={onRedeem} aria-label={`${buttonLabel}: ${voucher.name || voucher.code}`}>{buttonLabel}</button>
  </li>;
}

export default function RewardPoints() {
  const [params, setParams] = useSearchParams(); const page = Math.max(Number(params.get('page')) || 1, 1); const type = HISTORY_TYPES[params.get('type')] ? params.get('type') : '';
  const [account, setAccount] = useState(null); const [history, setHistory] = useState(null); const [catalog, setCatalog] = useState(null);
  const [errors, setErrors] = useState({ account: '', history: '', catalog: '', action: '' }); const [loading, setLoading] = useState({ account: true, history: true, catalog: true }); const [selected, setSelected] = useState(null); const [redeemingId, setRedeemingId] = useState(null);
  const mounted = useRef(true); const dialogRef = useRef(null);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => { const dialog = dialogRef.current; if (!dialog) return; if (selected && !dialog.open) dialog.showModal(); if (!selected && dialog.open) dialog.close(); }, [selected]);
  const updateQuery = useCallback((changes) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, String(value)) : next.delete(key)); setParams(next); }, [params, setParams]);
  const loadAccount = useCallback(async () => { setLoading((value) => ({ ...value, account: true })); try { const response = await loyaltyService.getLoyaltyAccount(); if (mounted.current) { setAccount(response?.data || null); setErrors((value) => ({ ...value, account: '' })); } } catch (error) { if (mounted.current) setErrors((value) => ({ ...value, account: errorMessage(error, 'Không thể tải điểm thưởng.') })); } finally { if (mounted.current) setLoading((value) => ({ ...value, account: false })); } }, []);
  const loadHistory = useCallback(async () => { setLoading((value) => ({ ...value, history: true })); try { const response = await loyaltyService.getPointHistory({ page, limit: PAGE_SIZE, type: type || undefined }); if (mounted.current) { setHistory({ data: Array.isArray(response?.data) ? response.data : [], pagination: response?.pagination || { page, totalPages: 0 } }); setErrors((value) => ({ ...value, history: '' })); } } catch (error) { if (mounted.current) setErrors((value) => ({ ...value, history: errorMessage(error, 'Không thể tải lịch sử điểm.') })); } finally { if (mounted.current) setLoading((value) => ({ ...value, history: false })); } }, [page, type]);
  const loadCatalog = useCallback(async () => { setLoading((value) => ({ ...value, catalog: true })); try { const response = await loyaltyService.getRewardCatalog(); if (mounted.current) { setCatalog(Array.isArray(response?.data) ? response.data : []); setErrors((value) => ({ ...value, catalog: '' })); } } catch (error) { if (mounted.current) setErrors((value) => ({ ...value, catalog: errorMessage(error, 'Không thể tải phần thưởng.') })); } finally { if (mounted.current) setLoading((value) => ({ ...value, catalog: false })); } }, []);
  const refreshAll = useCallback(() => Promise.all([loadAccount(), loadHistory(), loadCatalog()]), [loadAccount, loadHistory, loadCatalog]);
  useEffect(() => { loadAccount(); }, [loadAccount]); useEffect(() => { loadHistory(); }, [loadHistory]); useEffect(() => { loadCatalog(); }, [loadCatalog]); useFinancialRefresh(refreshAll);
  const redeem = async () => { if (!selected || redeemingId) return; setRedeemingId(selected.id); setErrors((value) => ({ ...value, action: '' })); try { await loyaltyService.redeemRewardCatalogItem(selected.id); if (!mounted.current) return; setSelected(null); invalidateFinancialData(); await refreshAll(); window.dispatchEvent(new CustomEvent('show-toast', { detail: { type: 'success', message: 'Đổi thưởng thành công. Voucher đã được thêm vào tài khoản của bạn.' } })); } catch (error) { if (mounted.current) { setErrors((value) => ({ ...value, action: redemptionMessage(error) })); await refreshAll(); } } finally { if (mounted.current) setRedeemingId(null); } };
  const balance = Number(account?.pointBalance || 0); const totalPages = Math.max(history?.pagination?.totalPages || 1, 1);
  return <main className="mx-auto max-w-container-max py-2"><header><h2 className="text-2xl font-bold text-[#333333]">Điểm thưởng</h2><p className="mt-2 text-sm text-ui-muted">Theo dõi điểm, lịch sử giao dịch và đổi thưởng trong một nơi.</p></header>
    <section className="mt-7" aria-labelledby="current-points"><h3 id="current-points" className="text-xl font-bold text-[#333333]">Điểm hiện tại</h3>{loading.account && !account ? <div className="mt-4 grid gap-4 sm:grid-cols-2"><Skeleton className="h-28" /><Skeleton className="h-28" /></div> : null}{errors.account ? <div className="mt-4 rounded border border-error bg-error-container p-4 text-sm" role="alert">{errors.account}<button className="ui-button-secondary ml-3" onClick={loadAccount}>Thử lại</button></div> : null}{account ? <div className="mt-4 grid gap-4 sm:grid-cols-2"><article className="ui-card p-5"><p className="text-sm text-ui-muted">Điểm hiện có</p><p className="mt-2 text-3xl font-bold text-[#333333]">{formatPoints(balance)} <span className="text-base">điểm</span></p></article><article className="ui-card p-5"><p className="text-sm text-ui-muted">Tổng điểm đã tích lũy</p><p className="mt-2 text-3xl font-bold text-[#333333]">{formatPoints(account.lifetimePoints)} <span className="text-base">điểm</span></p></article></div> : null}</section>
    <section className="mt-9 border-t border-[#eeeeee] pt-7" aria-labelledby="point-history"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h3 id="point-history" className="text-xl font-bold text-[#333333]">Lịch sử điểm</h3><p className="mt-1 text-sm text-ui-muted">Các giao dịch đã được ghi nhận.</p></div><label className="text-sm font-medium text-[#555555]">Loại giao dịch<select className="ui-select mt-1 w-full sm:w-auto" value={type} onChange={(event) => updateQuery({ type: event.target.value, page: 1 })}>{[{ value: '', label: 'Tất cả giao dịch' }, ...Object.entries(HISTORY_TYPES).map(([value, label]) => ({ value, label }))].map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div>{loading.history && !history ? <div className="mt-5 space-y-3"><Skeleton /><Skeleton /></div> : null}{errors.history ? <div className="mt-5 rounded border border-error bg-error-container p-4 text-sm" role="alert">{errors.history}<button className="ui-button-secondary ml-3" onClick={loadHistory}>Thử lại</button></div> : null}{history ? history.data.length ? <ul className="mt-5 space-y-3">{history.data.map((entry) => <li key={entry.id} className="ui-card grid gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p className="font-semibold text-[#333333]">{HISTORY_TYPES[entry.type] || 'Giao dịch điểm'}</p><p className="mt-1 text-sm text-ui-muted">{entry.reason || HISTORY_TYPES[entry.type]}</p><time className="mt-2 block text-xs text-[#777777]">{formatDate(entry.createdAt)}</time></div><strong className={Number(entry.pointsDelta) >= 0 ? 'text-[#2f6b45]' : 'text-[#9f2f2d]'}>{Number(entry.pointsDelta) > 0 ? '+' : ''}{formatPoints(entry.pointsDelta)} điểm</strong></li>)}</ul> : <div className="ui-empty-state mt-5" role="status">Chưa có giao dịch điểm.</div> : null}{history ? <div className="mt-5 flex items-center justify-between"><span className="text-sm text-ui-muted">Trang {page} / {totalPages}</span><div className="flex gap-2"><button className="ui-button-secondary" disabled={page <= 1} onClick={() => updateQuery({ page: page - 1 })}>Trước</button><button className="ui-button-secondary" disabled={page >= totalPages} onClick={() => updateQuery({ page: page + 1 })}>Sau</button></div></div> : null}</section>
    <section className="mt-9 border-t border-[#eeeeee] pt-7" aria-labelledby="rewards"><h3 id="rewards" className="text-xl font-bold text-[#333333]">Đổi điểm nhận thưởng</h3><p className="mt-1 text-sm text-ui-muted">Chọn ưu đãi phù hợp với số điểm hiện có của bạn.</p>{loading.catalog && !catalog ? <div className="mt-5 grid gap-4 sm:grid-cols-2"><Skeleton className="h-64" /><Skeleton className="h-64" /></div> : null}{errors.catalog ? <div className="mt-5 rounded border border-error bg-error-container p-4 text-sm" role="alert">{errors.catalog}<button className="ui-button-secondary ml-3" onClick={loadCatalog}>Thử lại</button></div> : null}{catalog ? catalog.length ? <ul className="mt-5 grid gap-4 sm:grid-cols-2">{catalog.map((item) => <RewardCard key={item.id} item={item} balance={balance} redeeming={redeemingId === item.id} onRedeem={() => { setErrors((value) => ({ ...value, action: '' })); setSelected(item); }} />)}</ul> : <div className="ui-empty-state mt-5">Hiện chưa có phần thưởng để đổi điểm.</div> : null}</section>
    <dialog ref={dialogRef} className="w-[calc(100%-2rem)] max-w-md rounded-[12px] border border-[#dddddd] p-0 text-[#333333] backdrop:bg-black/40" onCancel={(event) => { event.preventDefault(); if (!redeemingId) setSelected(null); }}>{selected ? <div className="p-5"><h3 className="text-xl font-bold">Xác nhận đổi thưởng</h3><p className="mt-3 text-sm leading-6">Bạn muốn đổi <strong>{selected.voucher?.name || selected.voucher?.code}</strong> với <strong>{formatPoints(selected.pointCost)} điểm</strong>.</p>{errors.action ? <p className="mt-3 text-sm text-[#9f2f2d]" role="alert">{errors.action}</p> : null}<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button className="ui-button-secondary" disabled={Boolean(redeemingId)} onClick={() => setSelected(null)}>Hủy</button><button className="ui-button-primary" disabled={Boolean(redeemingId)} onClick={redeem}>{redeemingId ? 'Đang đổi...' : 'Xác nhận đổi'}</button></div></div> : null}</dialog>
  </main>;
}
