import { useCallback, useEffect, useRef, useState } from 'react';
import { loyaltyService } from '../../services/api/loyaltyService';
import useFinancialRefresh, { invalidateFinancialData } from '../../hooks/useFinancialRefresh';

const money = (value) => `${new Intl.NumberFormat('vi-VN').format(Number(value || 0))} ₫`;
const date = (value) => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium' }).format(new Date(value)) : null;

export default function TierBenefits() {
  const [items, setItems] = useState(null); const [error, setError] = useState(''); const [claiming, setClaiming] = useState(null); const mounted = useRef(true);
  const load = useCallback(async () => { try { setError(''); const response = await loyaltyService.getTierBenefits(); if (mounted.current) setItems(Array.isArray(response?.data) ? response.data : []); } catch (requestError) { if (mounted.current) setError(requestError?.data?.error?.message || 'Không thể tải ưu đãi hạng thành viên.'); } }, []);
  useEffect(() => { mounted.current = true; load(); return () => { mounted.current = false; }; }, [load]); useFinancialRefresh(load);
  const claim = async (item) => { if (claiming) return; setClaiming(item.voucherDefinitionId); setError(''); try { await loyaltyService.claimTierBenefit(item.voucherDefinitionId); if (!mounted.current) return; invalidateFinancialData(); await load(); window.dispatchEvent(new CustomEvent('show-toast', { detail: { type: 'success', message: 'Đã nhận Voucher ưu đãi hạng thành viên.' } })); } catch (requestError) { if (mounted.current) setError(requestError?.data?.error?.message || 'Không thể nhận ưu đãi này.'); } finally { if (mounted.current) setClaiming(null); } };
  return <main className="mx-auto max-w-container-max py-2"><header><h2 className="text-2xl font-bold text-[#333333]">Ưu đãi hạng thành viên</h2><p className="mt-2 text-sm text-ui-muted">Các ưu đãi phù hợp với hạng hiện tại của bạn.</p></header>{error ? <div className="mt-6 rounded border border-error bg-error-container p-4 text-sm" role="alert">{error}<button className="ui-button-secondary ml-3" onClick={load}>Thử lại</button></div> : null}{items === null ? <div className="mt-6 grid gap-4 sm:grid-cols-2" aria-busy="true"><div className="ui-skeleton h-60 rounded-[12px]" /><div className="ui-skeleton h-60 rounded-[12px]" /></div> : items.length ? <ul className="mt-6 grid gap-4 sm:grid-cols-2">{items.map((item) => { const claimed = item.claimStatus === 'CLAIMED'; const expiry = item.fixedExpiresAt ? `Dùng đến ${date(item.fixedExpiresAt)}` : item.validityDaysAfterIssue ? `Có hiệu lực ${item.validityDaysAfterIssue} ngày sau khi nhận` : item.validTo ? `Nhận đến ${date(item.validTo)}` : null; return <li key={item.voucherDefinitionId} className="ui-card flex min-w-0 flex-col p-5"><div className="flex items-start justify-between gap-3"><span className="ui-badge">ƯU ĐÃI HẠNG</span><span className="ui-badge">{claimed ? 'CLAIMED' : 'CLAIMABLE'}</span></div><h3 className="mt-4 text-lg font-bold text-[#333333]">{item.title}</h3>{item.description ? <p className="mt-2 text-sm leading-6 text-ui-muted">{item.description}</p> : null}<dl className="mt-4 space-y-2 border-t border-[#eeeeee] pt-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-ui-muted">Ưu đãi</dt><dd className="font-semibold">{item.discountType === 'PERCENTAGE' ? `Giảm ${item.discountValueVnd}%` : `Giảm ${money(item.discountValueVnd)}`}</dd></div>{item.minimumOrderAmountVnd != null ? <div className="flex justify-between gap-3"><dt className="text-ui-muted">Đơn tối thiểu</dt><dd>{money(item.minimumOrderAmountVnd)}</dd></div> : null}{expiry ? <div className="flex justify-between gap-3"><dt className="text-ui-muted">Thời hạn</dt><dd className="text-right">{expiry}</dd></div> : null}</dl><button className="ui-button-primary mt-5 w-full" disabled={claimed || claiming === item.voucherDefinitionId} onClick={() => claim(item)}>{claimed ? 'Đã nhận' : claiming === item.voucherDefinitionId ? 'Đang nhận...' : 'Nhận ưu đãi'}</button></li>; })}</ul> : <div className="ui-empty-state mt-6" role="status">Hiện chưa có ưu đãi hạng thành viên phù hợp.</div>}</main>;
}
