import { useCallback, useEffect, useRef, useState } from 'react';
import useFinancialRefresh from '../../hooks/useFinancialRefresh';
import { loyaltyService } from '../../services/api/loyaltyService';

const TIERS = [{ key: 'BRONZE', label: 'Hạng Đồng', color: 'bg-[#9b7653]' }, { key: 'SILVER', label: 'Hạng Bạc', color: 'bg-[#87919a]' }, { key: 'GOLD', label: 'Hạng Vàng', color: 'bg-[#a97d23]' }, { key: 'DIAMOND', label: 'Hạng Kim Cương', color: 'bg-[#567c91]' }];
const money = (value) => `${new Intl.NumberFormat('vi-VN').format(Number(value || 0))} ₫`;

export default function Tier() {
  const [tier, setTier] = useState(null); const [benefits, setBenefits] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const mounted = useRef(true);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [tierResponse, benefitsResponse] = await Promise.all([loyaltyService.getTier(), loyaltyService.getTierBenefits()]); if (mounted.current) { setTier(tierResponse?.data || null); setBenefits(Array.isArray(benefitsResponse?.data) ? benefitsResponse.data : []); } } catch (requestError) { if (mounted.current) setError(requestError?.data?.error?.message || 'Không thể tải hạng thành viên.'); } finally { if (mounted.current) setLoading(false); } }, []);
  useEffect(() => { mounted.current = true; load(); return () => { mounted.current = false; }; }, [load]); useFinancialRefresh(load);
  if (loading && !tier) return <div className="space-y-4" aria-busy="true" aria-label="Đang tải hạng thành viên"><div className="ui-skeleton h-36 rounded-[12px]" /><div className="ui-skeleton h-28 rounded-[12px]" /></div>;
  if (error) return <div className="rounded border border-error bg-error-container p-4 text-sm" role="alert">{error}<button className="ui-button-secondary ml-3" onClick={load}>Thử lại</button></div>;
  if (!tier?.currentTier) return <div className="ui-empty-state" role="status">Chưa có thông tin hạng thành viên.</div>;
  const currentIndex = Math.max(TIERS.findIndex((item) => item.key === tier.currentTier), 0); const current = TIERS[currentIndex]; const next = TIERS.find((item) => item.key === tier.nextTier); const spend = Number(tier.eligibleCompletedMerchandiseAmountVnd || 0); const progress = next ? Math.min(100, Math.round((spend / Number(tier.nextTierThresholdVnd || 1)) * 100)) : 100;
  return <main className="mx-auto max-w-container-max py-2"><header><h2 className="text-2xl font-bold text-[#333333]">Hạng thành viên</h2><p className="mt-2 text-sm text-ui-muted">Hạng được xác nhận từ chi tiêu hoàn tất đủ điều kiện.</p></header><section className="mt-6"><article className="ui-card overflow-hidden"><div className={`h-1.5 ${current.color}`} /><div className="p-5"><p className="text-sm text-ui-muted">Hạng hiện tại</p><p className="mt-2 text-3xl font-bold text-[#333333]">{current.label}</p><p className="mt-4 text-sm text-[#777777]">Chi tiêu đủ điều kiện: {money(spend)}</p>{next ? <><div className="mt-5 flex justify-between gap-3 text-sm"><span>Tiến độ đến {next.label}</span><strong>{progress}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#eeeeea]"><div className={`h-full rounded-full ${next.color}`} style={{ width: `${progress}%` }} /></div><p className="mt-2 text-sm text-ui-muted">Còn {money(tier.remainingAmountVnd)} để đạt {next.label}.</p></> : <p className="mt-5 text-sm text-ui-muted">Bạn đang ở hạng cao nhất.</p>}</div></article></section><section className="mt-8 border-t border-[#eeeeee] pt-7"><h3 className="text-xl font-bold text-[#333333]">Lộ trình hạng</h3><ol className="mt-5 space-y-3">{TIERS.map((item, index) => <li key={item.key} className="flex items-center gap-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold text-white ${index <= currentIndex ? item.color : 'bg-[#c9c9c5]'}`}>{index + 1}</span><div className="ui-card flex min-w-0 flex-1 items-center justify-between p-3"><span className="font-semibold text-[#333333]">{item.label}</span><span className="text-xs text-ui-muted">{index <= currentIndex ? 'Đã đạt' : 'Chưa đạt'}</span></div></li>)}</ol></section><section className="mt-8 border-t border-[#eeeeee] pt-7"><h3 className="text-xl font-bold text-[#333333]">Ưu đãi hạng thành viên</h3><p className="mt-1 text-sm text-ui-muted">Các ưu đãi hiện phù hợp với hạng của bạn.</p>{benefits === null ? <div className="mt-4"><div className="ui-skeleton h-20 rounded-[12px]" /></div> : benefits.length ? <ul className="mt-4 grid gap-3 sm:grid-cols-2">{benefits.slice(0, 4).map((item) => <li key={item.voucherDefinitionId} className="ui-card p-4"><p className="ui-badge">ƯU ĐÃI HẠNG</p><p className="mt-3 font-semibold text-[#333333]">{item.title}</p><p className="mt-1 text-sm text-ui-muted">{item.discountType === 'PERCENTAGE' ? `Giảm ${item.discountValueVnd}%` : `Giảm ${money(item.discountValueVnd)}`}</p></li>)}</ul> : <div className="ui-empty-state mt-4">Hiện chưa có ưu đãi phù hợp.</div>}</section></main>;
}
