import assert from 'node:assert/strict';
import test from 'node:test';
import { decideClarification } from '../services/ai-advisor/clarification/clarification.policy.js';
import { clarificationDecisionSchema } from '../services/ai-advisor/clarification/clarification.schema.js';
const input = (overrides = {}) => ({ intent: { category: null, budget: { min: null, max: null }, confidence: 0.8, colors: [], materials: [] }, candidateCount: null, consecutiveClarificationCount: 0, askedFields: [], conflicts: [], noResultReasons: [], ...overrides });
test('policy clarifies missing category and broad category-only budget', () => { assert.equal(decideClarification(input()).field, 'category'); assert.equal(decideClarification(input({ intent: { category: 'sofa', budget: { min: null, max: null }, confidence: .8 }, candidateCount: 21 })).field, 'budget'); });
test('policy recommends category plus budget or acceptable candidate count without optional questions', () => { assert.equal(decideClarification(input({ intent: { category: 'sofa', budget: { min: null, max: 15000000 }, confidence: .2 }, candidateCount: 4 })).action, 'recommend'); assert.equal(decideClarification(input({ intent: { category: 'sofa', budget: { min: null, max: null }, confidence: .8 }, candidateCount: 2 })).action, 'recommend'); });
test('policy handles conflict, no-result, caps clarification, and does not repeat asked fields', () => { assert.equal(decideClarification(input({ conflicts: ['x'] })).field, 'conflict'); assert.equal(decideClarification(input({ candidateCount: 0 })).action, 'no_result_refinement'); assert.equal(decideClarification(input({ consecutiveClarificationCount: 2 })).action, 'recommend'); assert.equal(decideClarification(input({ askedFields: ['category'] })).action, 'recommend'); });
test('policy output is strict, bounded, and deterministic', () => { const result = decideClarification(input()); assert.deepEqual(result, decideClarification(input())); assert.deepEqual(clarificationDecisionSchema.parse(result), result); assert.ok(result.question.text.length <= 300 && result.question.options.length <= 6); assert.throws(() => clarificationDecisionSchema.parse({ ...result, extra: true })); });
