import { comparativePolicyInputSchema, comparativePolicySchema } from './policy.schema.js';

const empty = () => ({ action: 'none', hardFilters: { maxPriceExclusive: null, minPriceExclusive: null, excludedProductIds: [], sizeRelation: null, referenceSize: null, targetProductId: null }, softPreferences: { preferDifferentColor: false, referenceColors: [], preferDifferentMaterial: false, referenceMaterials: [], preferDifferentStyle: false, referenceStyles: [], preferSimilarCategory: null, similarColors: [], similarMaterials: [], similarStyles: [], similarPriceMin: null, similarPriceMax: null, preferDifferentProduct: false }, reference: { source: 'none', productId: null, effectivePrice: null } });
const handlers = {
  cheaper: (p, b) => priceRequired(p, b, 'maxPriceExclusive'),
  more_expensive: (p, b) => priceRequired(p, b, 'minPriceExclusive'),
  different_product: (p, b) => ({ ...b, hardFilters: { ...b.hardFilters, excludedProductIds: p.comparativeState.reference.productIds } }),
  different_color: (p, b) => ({ ...b, softPreferences: { ...b.softPreferences, preferDifferentColor: true, referenceColors: p.comparativeState.reference.colors } }),
  different_material: (p, b) => ({ ...b, softPreferences: { ...b.softPreferences, preferDifferentMaterial: true, referenceMaterials: p.comparativeState.reference.materials } }),
  different_style: (p, b) => ({ ...b, softPreferences: { ...b.softPreferences, preferDifferentStyle: true, referenceStyles: p.comparativeState.reference.style ? [p.comparativeState.reference.style] : [] } }),
  smaller: (p, b) => sizeRequired(p, b, 'smaller'), larger: (p, b) => sizeRequired(p, b, 'larger'),
  similar_to_previous: (p, b) => ({ ...b, softPreferences: { ...b.softPreferences, preferSimilarCategory: p.comparativeState.reference.category, similarColors: p.comparativeState.reference.colors, similarMaterials: p.comparativeState.reference.materials, similarStyles: p.comparativeState.reference.style ? [p.comparativeState.reference.style] : [], similarPriceMin: p.comparativeState.reference.minPrice, similarPriceMax: p.comparativeState.reference.maxPrice } }),
  ordinal_product: (p, b) => ({ ...b, action: 'stock_check', hardFilters: { ...b.hardFilters, targetProductId: p.comparativeState.reference.productId } }),
  stock_check: (p, b) => ({ ...b, action: 'stock_check', hardFilters: { ...b.hardFilters, targetProductId: p.comparativeState.reference.productId } })
};
const priceRequired = (p, b, field) => b.reference.effectivePrice === null ? { ...b, action: 'clarify_missing_reference' } : { ...b, hardFilters: { ...b.hardFilters, [field]: b.reference.effectivePrice } };
const sizeRequired = (p, b, relation) => p.comparativeState.reference.size === null ? { ...b, action: 'clarify_missing_reference' } : { ...b, hardFilters: { ...b.hardFilters, sizeRelation: relation, referenceSize: p.comparativeState.reference.size } };
export const buildComparativePolicy = (raw) => { const p = comparativePolicyInputSchema.parse(raw); if (p.comparativeState.type === 'none') return comparativePolicySchema.parse(empty()); const prices = new Map(p.productPrices.map(x => [x.productId, x.effectivePrice])); const target = p.comparativeState.reference.productId; const currentPrice = target && p.currentProduct?.id === target ? Number(p.currentProduct.finalPrice ?? p.currentProduct.displayPrice ?? p.currentProduct.price) : null; const effectivePrice = Number.isInteger(currentPrice) ? currentPrice : target ? prices.get(target) ?? null : null; let base = empty(); base.action = 'apply'; base.reference = { source: p.comparativeState.reference.source, productId: target, effectivePrice }; if (p.comparativeState.missingReference) base.action = 'clarify_missing_reference'; const handler = handlers[p.comparativeState.type]; const result = base.action === 'clarify_missing_reference' ? base : handler ? handler(p, base) : base; return comparativePolicySchema.parse(result); };
export const comparativePolicyHandlers = Object.freeze(handlers);
