const COUNTERS = new Set(['ai_requests_total', 'ai_requests_failed_total', 'ai_clarifications_total', 'ai_no_results_total', 'ai_relaxation_proposals_total', 'ai_relaxation_accepts_total', 'ai_relaxation_rejects_total', 'ai_recommendations_total', 'ai_provider_attempts_total', 'ai_provider_failures_total', 'ai_provider_fallbacks_total', 'ai_intent_fallbacks_total', 'ai_session_creations_total', 'ai_session_resets_total', 'ai_idempotency_hits_total', 'ai_rate_limit_rejections_total']);
const SUMMARIES = new Set(['ai_request_duration_ms', 'ai_nlu_duration_ms', 'ai_stage1_duration_ms', 'ai_stage2_duration_ms', 'ai_writer_duration_ms', 'ai_candidate_count', 'ai_recommendation_count']);
const LABELS = Object.freeze({ outcome: new Set(['recommendation', 'clarification', 'relaxation_proposal', 'terminal_no_result', 'rejected_relaxation', 'invalid_request', 'provider_fallback_success', 'failed', 'unknown']), provider: new Set(['gemini', 'none', 'unknown']), model: new Set(['gemini-flash-latest', 'custom', 'unknown']), reasonCode: new Set(['no_category_match', 'no_budget_match', 'no_attribute_match', 'excluded_only', 'out_of_stock_only', 'no_active_product', 'no_cheaper_match', 'no_more_expensive_match', 'no_different_product', 'no_smaller_match', 'no_larger_match', 'missing_comparative_reference', 'unknown']), clarificationField: new Set(['category', 'budget', 'room', 'style', 'size', 'colors', 'materials', 'conflict', 'relaxation', 'unknown']), intentType: new Set(['product_recommendation', 'catalog_question', 'unknown']), ownerType: new Set(['guest', 'authenticated', 'unknown']) });
const cleanLabels = (labels = {}) => Object.fromEntries(Object.entries(labels).filter(([key]) => LABELS[key]).map(([key, value]) => [key, LABELS[key].has(value) ? value : 'unknown']));
const key = (name, labels) => `${name}:${JSON.stringify(labels)}`;

export class AiMetricsRegistry {
  constructor() { this.counters = new Map(); this.summaries = new Map(); }
  increment(name, labels = {}) { if (!COUNTERS.has(name)) return; const safe = cleanLabels(labels); const metricKey = key(name, safe); const current = this.counters.get(metricKey) || { name, labels: safe, value: 0 }; current.value += 1; this.counters.set(metricKey, current); }
  observe(name, value, labels = {}) { if (!SUMMARIES.has(name) || !Number.isFinite(value) || value < 0) return; const safe = cleanLabels(labels); const metricKey = key(name, safe); const current = this.summaries.get(metricKey) || { name, labels: safe, count: 0, sum: 0, min: value, max: value }; current.count += 1; current.sum += value; current.min = Math.min(current.min, value); current.max = Math.max(current.max, value); this.summaries.set(metricKey, current); }
  recordEvent(event) {
    const labels = { outcome: event.outcome || undefined, provider: event.metadata.provider, model: event.metadata.model, reasonCode: event.metadata.reasonCode || undefined, clarificationField: event.metadata.clarificationField || undefined, intentType: event.metadata.intentType, ownerType: event.ownerType };
    const counters = { ai_request_started: 'ai_requests_total', ai_request_failed: 'ai_requests_failed_total', ai_clarification_returned: 'ai_clarifications_total', ai_terminal_no_result: 'ai_no_results_total', ai_relaxation_proposed: 'ai_relaxation_proposals_total', ai_relaxation_accepted: 'ai_relaxation_accepts_total', ai_relaxation_rejected: 'ai_relaxation_rejects_total', ai_recommendation_returned: 'ai_recommendations_total', ai_provider_attempt: 'ai_provider_attempts_total', ai_provider_failed: 'ai_provider_failures_total', ai_provider_fallback: 'ai_provider_fallbacks_total', ai_intent_fallback: 'ai_intent_fallbacks_total', ai_session_created: 'ai_session_creations_total', ai_session_reset: 'ai_session_resets_total', ai_idempotency_cache_hit: 'ai_idempotency_hits_total', ai_rate_limit_rejected: 'ai_rate_limit_rejections_total' };
    if (counters[event.eventName]) this.increment(counters[event.eventName], labels);
    if (event.eventName === 'ai_request_completed' && event.durationMs !== null) this.observe('ai_request_duration_ms', event.durationMs, labels);
    if (event.eventName === 'ai_intent_extracted' && event.durationMs !== null) this.observe('ai_nlu_duration_ms', event.durationMs, labels);
    if (event.eventName === 'ai_candidate_pipeline_completed') { if (event.durationMs !== null) this.observe('ai_stage1_duration_ms', event.durationMs, labels); if (event.metadata.candidateCount !== undefined) this.observe('ai_candidate_count', event.metadata.candidateCount, labels); }
    if (event.eventName === 'ai_recommendation_returned') { if (event.metadata.recommendationCount !== undefined) this.observe('ai_recommendation_count', event.metadata.recommendationCount, labels); if (event.durationMs !== null) this.observe('ai_stage2_duration_ms', event.durationMs, labels); }
    if (event.eventName === 'ai_provider_attempt' && event.metadata.providerOperation === 'writer' && event.durationMs !== null) this.observe('ai_writer_duration_ms', event.durationMs, labels);
  }
  snapshot() { return { counters: [...this.counters.values()].sort((a, b) => key(a.name, a.labels).localeCompare(key(b.name, b.labels))), summaries: [...this.summaries.values()].map((item) => ({ ...item, average: Number((item.sum / item.count).toFixed(2)) })).sort((a, b) => key(a.name, a.labels).localeCompare(key(b.name, b.labels))) }; }
}

export const aiMetrics = new AiMetricsRegistry();
export const snapshotAiMetrics = () => aiMetrics.snapshot();
